### ISSUE TITLE
Air-Co-Pred dataset

### ISSUE THREAD

**Issue by JerryBryant24** [WangzcBruce/DHD#5]
Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.

**Comment by narnehc** [comment]
> Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.

hello, have you encountered this error "KeyError: 'UAV_1_1'"? Do you know what to do about it?

**Comment by WangzcBruce** [comment]
> > Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.
> 
> hello, have you encountered this error "KeyError: 'UAV_1_1'"? Do you know what to do about it?

  modify config/dhd.yaml as --> NAMES : ['UAV_1', 'UAV_2', 'UAV_3', 'UAV_4']

**Comment by WangzcBruce** [comment]
> Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.

The structure of the Air-Co-Pred dataset is similar to that of the NuScenes dataset. Therefore, we directly utilize the existing dataloader for NuScenes.

**Comment by JerryBryant24** [comment]
> > Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.
> 
> The structure of the Air-Co-Pred dataset is similar to that of the NuScenes dataset. Therefore, we directly utilize the existing dataloader for NuScenes.

Thank you very much for your answers!

**Comment by narnehc** [comment]
> > > Dear author, I encountered some confusion when reviewing the code. I found that there were loadings of nuscenes and lyft datasets in the data.py file. I did not see the use of the Air-Co-Pred dataset.
> > 
> > 
> > hello, have you encountered this error "KeyError: 'UAV_1_1'"? Do you know what to do about it?
> 
> modify config/dhd.yaml as --> NAMES : ['UAV_1', 'UAV_2', 'UAV_3', 'UAV_4']
it has been totally solved, thank you very much!
